name: Deployment
on:
  push:
    branches:
      - mainline
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: vasanthdeveloper/mantu
          tags: latest
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Deploying to publicserver
        uses: appleboy/ssh-action@master
        env:
          COMMIT_MESSAGE: "$(git show-branch --no-name HEAD)"
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          envs: COMMIT_MESSAGE
          script: bash /home/vasanth/serverfiles/privateserver/scripts/deploy-mantu.bash "$COMMIT_MESSAGE"
